backend:
  name: github
  branch: main
  repo: asmockler/drew-tekulve
  # base_url: https://drew-tekulve.vercel.app
  base_url: http://localhost:3000
  auth_endpoint: api/auth_github
media_folder: "public/images"
public_folder: "/images"
collections:
  - name: "project"
    label: "Project"
    folder: "content/projects"
    create: true
    format: json
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Year", name: "year", widget: "string"}
      - label: "Category"
        name: "category"
        widget: "relation"
        collection: "project_category"
        value_field: title
        search_fields: ["title"]
      - label: Contributors
        name: contributors
        widget: list
        fields:
          - {label: Name, name: name, widget: string}
          - {label: Role, name: role, widget: string}
  - name: "project_category"
    label: "Project Category"
    folder: "content/project_categories"
    create: true
    format: json
    fields:
      - {label: "Title", name: "title", widget: "string"}
  - name: "pages"
    label: "Pages"
    files:
      - label: "About Page"
        name: "about"
        file: "content/pages/about.json"
        format: json
        fields:
          - label: Clients
            name: clients
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Logo, name: logo, widget: image}

